groupName: acme.molnett.net
logLevel: 6
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
image:
  repository: quay.io/molnett/cert-manager-webhook-gandi
  tag: 0.2.3
  pullPolicy: IfNotPresent
nameOverride: ''
fullnameOverride: ''
service:
  type: ClusterIP
  port: 443
features:
  apiPriorityAndFairness: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
